### ISSUE TITLE
Updated build not running

### ISSUE THREAD

**Issue by compsyguy** [roguelike2d/TekkenBot#13]
When I try the latest build, I get the following error:
Tekken pid acquired: 14768
Trying to acquire Tekken library in pid: 14768
ListProcessModules() Error on Module32First[6]
TekkenGame-Win64-Shipping.exe not found. Likely wrong process id.
Trying to acquire Tekken library in pid: 14768
ListProcessModules() Error on Module32First[6]
TekkenGame-Win64-Shipping.exe not found. Likely wrong process id.

I tried uncommenting the lines in: TekkenData/memory_address.config
Using neither option worked.

I can still run the 0.0.2-alpha version though

**Comment by roguelike2d** [comment]
That's interesting. Error 6 is an invalid handle error that's occurring while looking for the location of the Tekken7 dll in memory and that's happening before it uses any kind of pointer offset data from the config file. But none of that code has changed between versions 0.0.2 and 0.1.0.

Can you delete the config file and try the following:

Does the 0.0.2 version tell you the same process id as the 0.1.0 version?

Does rebooting Tekken change the displayed process id?

**Comment by compsyguy** [comment]
yes, they're showing the same pid, and rebooting Tekken does change the pid. I look in task manager and the pid is correct for TekkenGame-Win64-Shipping.exe

I am using python 3.5.. could that be the issue?

**Comment by roguelike2d** [comment]
The .exe launches off a standalone python included in the zip so that shouldn't be an issue.

Can you try the 0.0.6 version? If that works, it'll be a pretty good sign that the config file patch broke it... somehow.

**Comment by compsyguy** [comment]
I just loaded Python 3.4.3 and it works... it looks like its an issue with Python 3.5...

**Comment by roguelike2d** [comment]
That's... strangely disturbing.
