### ISSUE TITLE
 Beginner

### ISSUE THREAD

**Issue by pizzafight** [roguelike2d/TekkenBot#16]
Please tell me how to use this tool

**Comment by roguelike2d** [comment]
* Download and unzip the latest release from https://github.com/roguelike2d/TekkenBot/releases
* Run Tekken 7, set it to windowed mode. You can then (only after setting it to windowed!) set it to borderless if you wish.
* Run the exe you'll find in the downloaded folder.
* Some numbers will appear at the top of Tekken 7 when you click on it again. Understanding those numbers is beyond the scope of this tool, but there are many helpful frame data resources around the internet to use.

**Comment by pizzafight** [comment]
thank you!
