### ISSUE TITLE
"trying to acquire tekken library in pid : 14484 "

### ISSUE THREAD

**Issue by x22OnLSD** [roguelike2d/TekkenBot#21]
After _FrameDataLauncher.py launches i get : "Tekken pid acquired : 14484" . "Trying to acquire tekken library in pid : 14484" "List ProcessModules() Error on Module32First[6] and it gets spammed what does it mean?

**Comment by roguelike2d** [comment]
see issue https://github.com/roguelike2d/TekkenBot/issues/13
