### ISSUE TITLE
python 3.4.3 doesnt help 

### ISSUE THREAD

**Issue by x22OnLSD** [roguelike2d/TekkenBot#22]
so i uninstalled every other python and tried 3.4.3 still that error from the previuos issue :l

**Comment by compsyguy** [comment]
Double check the python version by just running the python executable.

Also, does the standalone exe work for the frame data overlay?

**Comment by x22OnLSD** [comment]
standalone works but only if i download the new one here

**Comment by roguelike2d** [comment]
This issue appears to be caused by using 32-bit Python. For some reason, the default Python 3.6 installer is 32-bit. So don't use that one.
