### ISSUE TITLE
Overlay 

### ISSUE THREAD

**Issue by omnislash79** [roguelike2d/TekkenBot#25]
how do i adjust the overlay? it is in window mode , but I have 3 monitors with different resolutions. 
<img width="955" alt="capture" src="https://user-images.githubusercontent.com/29907986/27847966-7dddb05e-610f-11e7-8a10-d78bb8f008ff.PNG">

**Comment by roguelike2d** [comment]
https://askleo.com/i_cant_see_the_top_of_a_window_so_i_cant_minimize_maximize_or_close_what_can_i_do-2/
