### ISSUE TITLE
No fight detected. Gamestate not updated.

### ISSUE THREAD

**Issue by senseirain** [roguelike2d/TekkenBot#3]
No fight detected. Gamestate not updated.

**Comment by senseirain** [comment]
HELP!? How do u fix this?
![111111](https://user-images.githubusercontent.com/21225106/27735863-30aa7882-5dd4-11e7-8549-cead4304a0bc.jpg)

**Comment by Sewake** [comment]
I think you need to change the 'player_data_pointer_offset' variable in MemoryAddressEnum.py, you can find this with the help of Cheat Engine.

Just look l127 in the TekkenGameState.py

```
player_data_base_address = self.GetValueFromAddress(processHandle, self.module_address + MemoryAddressOffsets.player_data_pointer_offset.value, is64bit = True)
                if player_data_base_address == 0:
                    print("No fight detected. Gamestate not updated.")
                    self.needReaquireGameState = True
```

**Comment by senseirain** [comment]
how?

**Comment by Sewake** [comment]
Well if you don't details more about your game version, etc. it's difficult to help you

Have you read the "Updating Memory Addresses with Cheat Engine after patches" part in README.md ?

**Try uncomment this line :** 

`#player_data_pointer_offset = 0x0337A450 #pc patch 0`

and comment the other one above, this might mean you still have pc patch 0 

**If this doesn't work:**

Cheat Engine is a tool that helps you figure out the variable used by the game, and their adresses.

1. Download Cheat Engine and check Tekken 7 with it

2. Go in training mode, check a row with a value of 32769 when you're character is standing Standing, and a value of 32770

3. When you have that row, copy/paste the adress inside the variable

**Comment by senseirain** [comment]
I'm using nonsteam I think it's v1.0 ?,..

**Comment by senseirain** [comment]
I'm noob with this,.. 
I dunno where to find the " #player_data_pointer_offset = 0x0337A450 #pc patch 0 "
And where can I find the 32769 value? Imma scan it or in the memory viewer?
Can u teach me step by step?,.. U have facebook or messenger or discord?
![111111](https://user-images.githubusercontent.com/21225106/27741022-6aac7a6e-5de6-11e7-8f08-9f692f362fe0.jpg)

**Comment by Sewake** [comment]
Well, I told you 'player_data_pointer_offset' variable is in MemoryAddressEnum.py
Delete the # from #player_data_pointer_offset
and add it just before 'player_data_pointer_offset =  0x03360450 #pc patch 1', 

So you resort with this:
```
#player_data_pointer_offset =  0x03360450 #pc patch 1
player_data_pointer_offset = 0x0337A450 #pc patch 0
```
Relaunch the game, maybe you will need to use the .bat file again

CheatEngine was only in the case this doesn't solve your problem

**Comment by senseirain** [comment]
Aw Sorry,.. but I don't have any MemoryAddressEnum.py or the ".bat" file here,..
![111111](https://user-images.githubusercontent.com/21225106/27741641-61581cdc-5de8-11e7-80a1-0e33a18c2e44.jpg)

**Comment by senseirain** [comment]
Like this right?
![111111](https://user-images.githubusercontent.com/21225106/27742441-3954906e-5deb-11e7-9129-ad65e7bd58f0.jpg)

**Comment by Sewake** [comment]
Yes I think it should solve the problem :)
But to be honnest I couldn't even test the overlay myself, I'm not at home for the moment so I can only read the source code and find a solution

Did this work ?

**Comment by senseirain** [comment]
Didn't work still the same,..

**Comment by Sewake** [comment]
Well an easy way to solve this is just to update the game to the latest version, like this you wouldn't need to change the variable

But I think the reason why it's still the same is because you need to recompile the .py files
I don't know if you're familiar with python or programmation, but when a .py file is compiled, .pyc files are created, so basically the program still reading the old file version

Sorry I can't help you more :/ hope you will find a solution soon

**Comment by senseirain** [comment]
Nyahahaha I'm Using Cracked Version Can't Update,.. xDD

**Comment by senseirain** [comment]
T_T

**Comment by Sewake** [comment]
Yeah I know that's why I suggested to you the tricky solution aha, well try a way or another to recompile the python files and it should be good

**Comment by Sewake** [comment]
I'm not so familiar with batch files, but what does it do if you double click on it, have you tried it ?
It is not supposed to clean all the .pyc files and recompile .py files ?

build_project.bat

**Comment by senseirain** [comment]
Yeah I did that earlier,..

**Comment by roguelike2d** [comment]
Okay, I've added a config file to the next release in TekkenData/memory_address.config. Uncommenting the values inside should allow cheat engine users, pirates, and legit users who haven't patched in a month to use older versions without having to rebuild the entire project.
