### ISSUE TITLE
The Tekken 7 bot does not work.

### ISSUE THREAD

**Issue by AEEEE15** [roguelike2d/TekkenBot#30]
Does not start at all. nothing happen by clicking the build_project.bat. it autoclose.

**Comment by AEEEE15** [comment]
if the bot does not work like thetoolassisted one then it's an useless trash tool. not helping at all.

**Comment by roguelike2d** [comment]
Your feedback has been acknowledged.

**Comment by AEEEE15** [comment]
Meh. put your tool where the sun does not shine. glad I didn't donated to you.

**Comment by AEEEE15** [comment]
Useless tool. you asshole.
