### ISSUE TITLE
opp/bot xyz not showing correct value

### ISSUE THREAD

**Issue by lovegu** [roguelike2d/TekkenBot#31]
you're dropping your IsDataAFloat() at the end of GetValueFromFrame() when gathering player data.

p1_value = self.GetValueFromFrame(player_data_frame, offset_enum.value)
p2_value = self.GetValueFromFrame(player_data_frame, offset_enum.value, MemoryAddressOffsets.p2_data_offset.value)

to 

p1_value = self.GetValueFromFrame(player_data_frame, offset_enum.value, 0x0, IsDataAFloat(offset_enum))
p2_value = self.GetValueFromFrame(player_data_frame, offset_enum.value, MemoryAddressOffsets.p2_data_offset.value,IsDataAFloat(offset_enum))

**Comment by roguelike2d** [comment]
Thanks, I had actually forgotten those were still in PlayerDataAddress and hadn't been refactored out.
