### ISSUE TITLE
Start Bot Please

### ISSUE THREAD

**Issue by Neverlite** [roguelike2d/TekkenBot#32]
Hey bro,

I have just 3 ask, just how to run the BOT for play with this ? We cant atm ? For later we can ? Thanks ! ;)

**Comment by roguelike2d** [comment]
Currently, TekkenBot can input commands, but has no ability to 'think' or improve at Tekken. I'm working on hooking up some kind of learning ability, but that's on the backburner for now, there's no ETA.
