### ISSUE TITLE
I dont see data info ingame

### ISSUE THREAD

**Issue by Flafy85** [roguelike2d/TekkenBot#34]
I dont see data ingame.. only when I Alt + tab game... and when I bring game up from alt tab I can on a sec see data info on top but not in the game...

**Comment by lovegu** [comment]
AFAIK it doesnt work with full screen
change graphic settings to borderless or window and try it again..

**Comment by roguelike2d** [comment]
Yeah, doesn't work full screen and to get windowed borderless you have to switch to windowed, then to borderless. I should probably print that in the console.

**Comment by Flafy85** [comment]
Thank you gys.. now its working I put the game on borderles....
