### ISSUE TITLE
Error code 299 {Steam patch broke the bot}

### ISSUE THREAD

**Issue by Joakes19** [roguelike2d/TekkenBot#36]
Hi! I'm having a problem with the bot.

When launching I get an error code and the bot overlay flashes without showing any data (img inc).
Any help?

Thanks!

![error299](https://user-images.githubusercontent.com/30535015/28731801-4617eea2-73cd-11e7-8a7c-ec532e78dc8e.png)

**Comment by poohoo123** [comment]
same issue, today was a small update mb it's connected (they added some new cosmetics)

**Comment by lovegu** [comment]
when there's an update, new offset should be found and applied to the bot
need to wait until @roguelike2d updates the offset
or you can find it by yourself

**Comment by Joakes19** [comment]
@lovegu Thanks! I thought it would be just me having the problem, good to know!

**Comment by Joakes19** [comment]
@poohoo123 Thank you! Glad it wasnt just me being stupid lol

**Comment by Joakes19** [comment]
@lovegu Thanks! I thought it would be just me having the problem, good to know!

**Comment by roguelike2d** [comment]
New release has been updated for the steam patch.
