### ISSUE TITLE
Any chance of gui version of punisher ? to test

### ISSUE THREAD

**Issue by excision1** [roguelike2d/TekkenBot#38]
no clue how to test it using python tried out the frame trap works a treat curious how the punisher 1 works if no gui version quick run down how to test ?

**Comment by roguelike2d** [comment]
I've added a very sparse GUI_PunisherBot.py for those who want to see it in action. It uses punish strings from TekkenData/CharacterData. The strings haven't been updated in a month and there have been several changes to the notation since then so the combos may not work.

**Comment by excision1** [comment]
ahh thanks alot bud will give it a nice check out tested the frame trap 1 against cpu on ultra hard and changed block all lows to parry all lows was a fun sight to watch lol
