### ISSUE TITLE
Possible to add strings etc to character data

### ISSUE THREAD

**Issue by excision1** [roguelike2d/TekkenBot#39]
trying to update ya character data with different punishers etc off blocks but to no avail wondering if am missing something or doing the string data wrong etc 

so say a WS  punish 
"13":">, +1, >, +2, >" thats the default  say i wanted to change it to do this instead  

  just a test example  "13":">, +1, >, +2, >, EWGF, >, S!,  dash, b24, >"
is that possible or am i missing something possible to just import notations strings from a website then add stuff such as S! etc

**Comment by roguelike2d** [comment]
It's not quite that friendly yet. You're going to have to mess with the timings a bunch. See https://github.com/roguelike2d/TekkenBot/issues/18#issuecomment-313352508 for some explanation of the notation. But really, it's not released yet so support on it is going to be pretty minimal.

**Comment by excision1** [comment]
no problem bud seems it may be a case of having to just add more >> and more  frames   and S! to get normal strings to work proper then will keep me busy testing it all out  deffo a fun tool to learn from if i manage to get some good punishes going will edit this post incase ya wanting to add them to the tekken data in future
