### ISSUE TITLE
frame data not displaying

### ISSUE THREAD

**Issue by fakeusername13** [roguelike2d/TekkenBot#41]
The window shows up in game but the frame data only shows up after i throw an attack 5-6 times as if the program is lagging or something. I've tried running as admin and starting it before or after i start tekken and nothing seems to help. Any ideas as to why this is happening and how to fix it?

**Comment by roguelike2d** [comment]
Sounds like a performance issue. TekkenBot is pretty poorly optimized right now and requires a decent chunk of cpu. Are you getting 60 fps in Tekken 7?

**Comment by fakeusername13** [comment]
yeah i get 60 fps but i will mess with some setting and see if that helps thanks for answering
