### ISSUE TITLE
TekkenBotPrime Ain't working

### ISSUE THREAD

**Issue by senseirain** [roguelike2d/TekkenBot#44]
The Tool is not working on Tekken 7 Older version (Cracked)
![1](https://user-images.githubusercontent.com/21225106/29498407-336b8aa2-862e-11e7-8c14-cc54be4ee1d9.jpg)

**Comment by roguelike2d** [comment]
You might try TekkenBotFrameDataOverlay v0.2,2 , after that they patched the game and changed all the static offsets.

As far as updating it goes, the current version takes a dozen or so pointers to work and I'm not really interested in doubling the work of maintaining pointers by adding cracked Tekken to my list. If anyone really altruistic and motivated uses cheat engine and the source code to find the right addresses and posts them, I'll see about adding them into the released version.

**Comment by senseirain** [comment]
(T_T) I can help if u teach me,..
