### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by ALEScheps** [roguelike2d/TekkenBot#45]
i launch both tekken and tekkenbotprime,
it finds the correct PID
i go into practice mode
doesnt show any frame data (showing ? instead of + or - frames and no history either)

**Comment by roguelike2d** [comment]
There was a patch Tuesday that produced that behavior, is your version of Tekken 7 and TekkenBot both up to date?

**Comment by ALEScheps** [comment]
updated, works again
thanks
