### ISSUE TITLE
how to force it to always pick the character on the left rather than right or enter a name of character ?

### ISSUE THREAD

**Issue by excision1** [roguelike2d/TekkenBot#46]
#this is for frametrap punisher etc and framedata ive set 
class TekkenGameState:
    def __init__(self):
        self.gameReader = TekkenGameReader()
        self.isPlayer2 = False

        self.duplicateFrameObtained = 0
        self.stateLog = []
        self.mirroredStateLog = []

        self.isMirrored = True

        self.futureStateLog = None
so it picks left side instead of right but its like a 30% chance it works for some reason thought id ask any easier way to make it put bot on 1 side rather than the other 

and to say if i wanted it to perform a different action instead of block how would i go about adding it 

like these lines here
 def BlockAllAttacks(gameState: TekkenGameState, botCommands:BotCommands):
        if gameState.IsOppAttacking():
            if gameState.IsOppAttackLow():
                botCommands.LowParry(max(0, gameState.GetOppTimeUntilImpact()))
            else:
                botCommands.BlockMidFull(max(0, gameState.GetOppTimeUntilImpact())) maybe change this 1 to a move like  botCommands.("Name of move goes here ")(max(0, gameState.GetOppTimeUntilImpact()))
like i managed to change the block low to parry low fine cus u already had it in commands but was wondering how to add a specific move etc  
 
i did a small edit managed to get sorta what i was wanting just changed block to do a certain move a lil inconsistent but works i guess still no clue how to make it be 1 side tho

**Comment by roguelike2d** [comment]
Whether it controls the left or right character is controlled by passing True or False to the TekkenBotLauncher constructor. So in GUI_FrameTrapBot.py, it controls the right character because of the line `self.launcher = TekkenBotLauncher(BotFrameTrap, False), I think True will make it control player 1.

There's no easy way to make it perform actions without additional coding at this point.
