### ISSUE TITLE
Overlay showing up when game loads, then disappears.

### ISSUE THREAD

**Issue by kuehlc** [roguelike2d/TekkenBot#5]
I tried running Tekken 7 in multiple modes, including borderless, and the overlay disappears every time. The program still runs, and I see the frame data if I alt+tab out of the game, but the overlay doesn't show.

**Comment by compsyguy** [comment]
Does the overlay show up at all when you run it? 
If it does show up, when does it disappear?

**Comment by kuehlc** [comment]
It appears when the game initially goes full screen on launch, then
disappears as soon as the next image or loading screen of the game pops up.

**Comment by compsyguy** [comment]
Are you launching the overlay before Tekken?  If you are, what happens when you launch the overlay after Tekken is already loaded and in a match/practice mode?

**Comment by kuehlc** [comment]
I launch tekken, then I launch the overlay. Then I reload Tekken ( this is
where the pop up and disappearing occurs). I've then tried closing and
reopening the overlay while in a practice match. The program works and
registers data, but the overlay just doesn't show.

**Comment by compsyguy** [comment]
Why are you reloading Tekken? Why not just Launch Tekken, launch the overlay then use it?

Or when you say you reload Tekken, are you just switching back to it?

**Comment by kuehlc** [comment]
I've tried both. I was watching Aris stream and he said something about
relaunching the game. That might have been related to his streaming tools
though in order for the chat to see.

**Comment by roguelike2d** [comment]
Can you let me know if either of the following help the issue:
1. There's an issue where you have to be in windowed mode *before* borderless mode, otherwise it stays in  fullscreen even though it says borderless.
2. Change 'minimize_on_loss_focus' from 1 to 0 in TekkenData/frame_data_overlay.config

**Comment by kuehlc** [comment]
The first option solved the problem. Thanks man. Did you learn Python from
school or on your own?
