### ISSUE TITLE
The feasibility of modding Tekken in this way.

### ISSUE THREAD

**Issue by MintPaw** [roguelike2d/TekkenBot#56]
This is more of a question for devs.

I see that you can get memory from hardcoded address this way, and that they're gotten from Cheat Engine. What more can you do? Can you call functions maybe or press button? Something simple like force restart training (Select+A)

Or could it be taken further is a player lobby, like if both players were running a modified version of Tekkenbot to make a match have an infinite timer, and heal damage? To create some kind of online training mode.

I'm considering attempting this, but how realistic is that, and what would you suggest looking at first?

**Comment by lovegu** [comment]
Infinite timer and infinite health can be activated by both players using trainer to activate infinite options.

if used by one player and the other player does not, then there will be sync error and gets disconnected before the match ends.

You cannot write memory and run input by python without code injection.
