### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kuehlc** [roguelike2d/TekkenBot#6]
Where did you learn how to do things like this? I am in my last year of school for computer science for Java. I had an intro to python class, so I need to do a refresher, but I was wondering if you'd be willing to share some knowledge. I don't want to put my email on a public site like this, so let me know if you think of something. Or, if you have Twitter, feel free to message me there. @Kuehl17

**Comment by roguelike2d** [comment]
I don't have any secrets. I started off this project having no idea how to do it and used google a lot.
