### ISSUE TITLE
Question Important

### ISSUE THREAD

**Issue by x22OnLSD** [roguelike2d/TekkenBot#8]
Hey , since ur online rn maybe u can help me So the FrameData Overlay works Perfect But how to use the bot? like which exe do i need to start to use the bot which plays automatically i only can find the framedata overlay.exe

**Comment by roguelike2d** [comment]
You can't use the bots right now unless you run them from the source code. There's no release of them.

**Comment by x22OnLSD** [comment]
How can i run them from the source code / where is the source code?
