### ISSUE TITLE
Not installing, python 3.6

### ISSUE THREAD

**Issue by sweetclimusic** [roguelike2d/TekkenBot#9]
Do you want issuse or pull requests?  The Readme should be updated to inform users pyinstaller doesn't support python 3.6 and latest version they can install is 3.5.3 This is what version I had to installed to get it running and it can't be built with the latest python. If like me they don't have python installed will just grab the latest version and will be stumped what it doesn't build.
### Prerequisites ( Update to include python is needed)
Python installed on your windows PC, Tekken Bot is developed on Python 3.4.3, this is the recommend version to install. Please not Pyinstaller doesn't support Python 3.6 currently the highest release version you can install is Python 3.5.3
### Installation
You will need to have a version of Python installed on your Windows pc, download the python installer for Python 3.4.3 from [www.python.org](https://www.python.org/downloads/windows/) You will have to navigate to the full windows download list and scroll down to find the corect version. Follow the steps in the installer and ensure you check add to Path.  once Python is installed run the cmd prompt (Windows KEY + R, then type in "cmd"). Once cmd is up and running installed pyinstaller by typing in pip install pyinstaller.  Once that is done close the cmd window navigate to the Tekken Bot folder and run the windows bat file "build_project.bat"

**Comment by roguelike2d** [comment]
If you have python installed, you should be able to just run 'python GUI_FrameDataOverlay.py' to launch the overlay.

I'll add a note in the readme that the distributable is built with 3.4.3.
